"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardBody, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { Tables } from "@/types/database.types";
import { updateOrganizationDetails } from "@/lib/organization-actions";

export function OrganizationForm({ organization, memberCount, ownerName, role }: { organization: Tables<"organizations">; memberCount: number; ownerName: string; role: string }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState<string | null>(null);
  const editable = role === "owner" || role === "admin";
  function submit(formData: FormData) { setMessage(null); startTransition(async () => { const result = await updateOrganizationDetails(formData); setMessage(result.error || (result.success ? "Organization settings updated." : null)); if (result.success) router.refresh(); }); }
  return <div className="max-w-2xl space-y-6"><Card><CardHeader><CardTitle>Organization profile</CardTitle><CardDescription>{memberCount} member{memberCount === 1 ? "" : "s"} · Owner: {ownerName}</CardDescription></CardHeader><CardBody><form action={submit} className="space-y-4"><label className="block space-y-1.5 text-sm font-medium">Organization name<input name="name" defaultValue={organization.name} disabled={!editable} required className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm disabled:opacity-60" /></label><label className="block space-y-1.5 text-sm font-medium">Slug<input name="slug" defaultValue={organization.slug ?? ""} disabled={!editable} className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm disabled:opacity-60" /></label><label className="block space-y-1.5 text-sm font-medium">Contact email<input name="contactEmail" type="email" defaultValue={organization.contact_email ?? ""} disabled={!editable} className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm disabled:opacity-60" /></label><div className="grid grid-cols-2 gap-4"><label className="block space-y-1.5 text-sm font-medium">Timezone<select name="timezone" defaultValue={organization.timezone} disabled={!editable} className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm disabled:opacity-60"><option>America/New_York</option><option>America/Chicago</option><option>America/Denver</option><option>America/Los_Angeles</option></select></label><label className="block space-y-1.5 text-sm font-medium">Currency<input name="currency" defaultValue={organization.currency} disabled={!editable} maxLength={3} className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm uppercase disabled:opacity-60" /></label></div>{message && <div role="status" className={`rounded-lg border px-4 py-3 text-sm ${message.includes("updated") ? "border-success/20 bg-success/10 text-success" : "border-danger/20 bg-danger/10 text-danger"}`}>{message}</div>}{editable && <Button type="submit" isLoading={pending} loadingText="Saving...">Save organization</Button>}</form></CardBody></Card><Card><CardHeader><CardTitle>Workspace details</CardTitle></CardHeader><CardBody className="space-y-3 text-sm"><p><span className="text-muted-foreground">Your role:</span> <span className="font-medium capitalize">{role}</span></p><p><span className="text-muted-foreground">Created:</span> <span className="font-medium">{new Date(organization.created_at).toLocaleDateString()}</span></p></CardBody></Card></div>;
}
